apiVersion: apps/v1
kind: Deployment
metadata: 
  name: webapitest-dp
  labels:
    microservice: webapitest
spec:
  replicas: 3
  selector:
    matchLabels:  
      microservice: webapitest
  template:
    metadata:
      labels:
        microservice: webapitest
        # role: webapitest
    spec:
      containers:
      - name: webapitest
        image: nottoday/webapitest:latest
        imagePullPolicy:  Always
        ports:
          - containerPort:  80

