apiVersion: apps/v1
kind: Deployment
metadata: 
  name: webapitest-dp
  labels:
    microservice: webapitest
spec:
  replicas: 1
  selector:
    matchLabels:  
      microservice: webapitest
  template:
    metadata:
      labels:
        microservice: webapitest
        # role: webapitest
    spec:
      containers:
      - name: webapitest
        image: nottoday/webapitest:latest
        imagePullPolicy:  Always
        ports:
          - containerPort:  80
        env:
        - name: PASSWORD
          value: "password"
        resources:
          requests:
            memory: "64Mi"
            cpu:  "200m"
          limits:
            memory: "128Mi"
            cpu:  "500m"
