apiVersion: v1
kind: ReplicationController
metadata:
  name: webapitest-rc
spec:
  replicas: 2
  template:
    metadata:
        labels:
          role: webapitest
    spec:
      containers:
      - name: webapitest
        image: nottoday/webapitest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
